name: Test FIPS

on:
  pull_request:
    path:
    - datadog_checks_base/datadog_checks/**
  schedule:
    - cron: '0 0,8,16 * * *'

defaults:
  run:
    shell: bash

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
        agent-image: ["datadog/agent-dev:master-py3", "datadog/agent-dev:master-fips", "datadog/agent-dev:master-py3-win-servercore"]
        exclude:
          - os: windows-2022
            agent-image: "datadog/agent-dev:master-fips"
          - os: windows-2022
            agent-image: "datadog/agent-dev:master-py3"
          - os: ubuntu-22.04
            agent-image: "datadog/agent-dev:master-py3-win-servercore"
    runs-on: ${{ matrix.os }}
    name: "Test FIPS"

    env:
      FORCE_COLOR: "1"
      PYTHON_VERSION: "3.12"
      AGENT_IMAGE: "${{ matrix.agent-image }}"

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: "${{ env.PYTHON_VERSION }}"
        cache: 'pip'

    - name: Install pytest
      run: |
        pip install pytest

    - name: Set up containers
      run: |
        docker compose -f .github/workflows/fips/compose/docker-compose.yml up -d

    - name: Run tests
      run: |
        pytest -v .github/workflows/fips/tests

